spring:
  application:
  name: cashflow

  datasource:
    url: jdbc:postgresql://localhost:5432/moneta
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  springdoc:
    swagger-ui:
      path: /swagger-ui.html